apiVersion: 1

datasources:
  - name: InfluxDB - WH1
    uid: influxdb-wh1-customer
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: ${INFLUXDB_ORG}
      defaultBucket: ${INFLUXDB_CUSTOMER_BUCKET}
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUXDB_WH1_READ_TOKEN}
