substitutions:
  name: "fancoil-08"
  friendly_name: "Fancoil 08"
  room: "CustoemrService"

packages:
  base:
    url: https://github.com/daggy72/esphome-fancoil
    ref: main
    file: fancoil-base.yaml
    refresh: 0s
