substitutions:
  name: "fancoil-07"
  friendly_name: "Fancoil 07"
  room: "CustomerService"

packages:
  base:
    url: https://github.com/daggy72/esphome-fancoil
    ref: main
    file: fancoil-base.yaml
    refresh: 0s
